import logging

log = logging.getLogger("coingecko")

STABLECOINS = {"USDT", "USDC", "DAI", "BUSD", "TUSD", "FDUSD", "PYUSD", "USD", "USDS",
               "USDE", "PYUSD", "RLUSD", "USD1", "USDD", "USD0", "GHO"}

# Exchange-specific tickers NOT in the CoinGecko top-N market-cap list.
# Edit this when you trade a coin that isn't in the auto-generated TOP_COINS below.
EXTRA_COINS = {
    "PROVE": "succinct",
}

# Auto-generated by scripts/refresh_coin_map.py — top 100 by market cap.
# Fetched 2026-05-31 UTC. Re-run that script to refresh.
TOP_COINS = {
    "BTC": "bitcoin",
    "ETH": "ethereum",
    "USDT": "tether",
    "BNB": "binancecoin",
    "XRP": "ripple",
    "USDC": "usd-coin",
    "SOL": "solana",
    "TRX": "tron",
    "FIGR_HELOC": "figure-heloc",
    "DOGE": "dogecoin",
    "HYPE": "hyperliquid",
    "USDS": "usds",
    "LEO": "leo-token",
    "ZEC": "zcash",
    "RAIN": "rain",
    "ADA": "cardano",
    "XLM": "stellar",
    "XMR": "monero",
    "LINK": "chainlink",
    "WBT": "whitebit",
    "BCH": "bitcoin-cash",
    "CC": "canton-network",
    "TON": "the-open-network",
    "USD1": "usd1-wlfi",
    "USDE": "ethena-usde",
    "DAI": "dai",
    "HBAR": "hedera-hashgraph",
    "LTC": "litecoin",
    "AVAX": "avalanche-2",
    "M": "memecore",
    "SUI": "sui",
    "LAB": "lab",
    "SHIB": "shiba-inu",
    "PYUSD": "paypal-usd",
    "CRO": "crypto-com-chain",
    "USYC": "hashnote-usyc",
    "NEAR": "near",
    "XAUT": "tether-gold",
    "USDG": "global-dollar",
    "TAO": "bittensor",
    "BUIDL": "blackrock-usd-institutional-digital-liquidity-fund",
    "MNT": "mantle",
    "PAXG": "pax-gold",
    "USDY": "ondo-us-dollar-yield",
    "DOT": "polkadot",
    "ASTER": "aster-2",
    "OKB": "okb",
    "UNI": "uniswap",
    "WLFI": "world-liberty-financial",
    "ONDO": "ondo-finance",
    "RLUSD": "ripple-usd",
    "USDF": "falcon-finance",
    "HTX": "htx-dao",
    "PI": "pi-network",
    "BGB": "bitget-token",
    "SKY": "sky",
    "ICP": "internet-computer",
    "PEPE": "pepe",
    "USDD": "usdd",
    "MORPHO": "morpho",
    "BFUSD": "bfusd",
    "ETC": "ethereum-classic",
    "AAVE": "aave",
    "WLD": "worldcoin-wld",
    "ALGO": "algorand",
    "RENDER": "render-token",
    "KCS": "kucoin-shares",
    "U": "united-stables",
    "USDTB": "usdtb",
    "QNT": "quant-network",
    "ATOM": "cosmos",
    "EUTBL": "eutbl",
    "BCAP": "blockchain-capital",
    "POL": "polygon-ecosystem-token",
    "USTB": "superstate-short-duration-us-government-securities-fund-ustb",
    "NEXO": "nexo",
    "JTRSY": "janus-henderson-anemoy-treasury-fund",
    "DEXE": "dexe",
    "STABLE": "stable-2",
    "KAS": "kaspa",
    "ENA": "ethena",
    "VVV": "venice-token",
    "GT": "gatechain-token",
    "APT": "aptos",
    "JST": "just",
    "FIL": "filecoin",
    "FLR": "flare-networks",
    "XDC": "xdce-crowd-sale",
    "ARB": "arbitrum",
    "INJ": "injective-protocol",
    "PUMP": "pump-fun",
    "NIGHT": "midnight-3",
    "FET": "fetch-ai",
    "H": "humanity",
    "BDX": "beldex",
    "JUP": "jupiter-exchange-solana",
    "GHO": "gho",
    "HASH": "hash-2",
    "USD0": "usual-usd",
    "APXUSD": "apxusd",
}

COIN_IDS = {**TOP_COINS, **EXTRA_COINS}


class CoinResolver:
    """Pure-Python ticker → CoinGecko-ID resolver. No HTTP calls anywhere."""

    def __init__(self, overrides: dict[str, str] | None = None) -> None:
        self._map = dict(COIN_IDS)
        if overrides:
            self._map.update({k.upper(): v for k, v in overrides.items()})
        self._warned: set[str] = set()

    def resolve(self, symbol: str) -> str | None:
        sym_u = symbol.upper()
        cg_id = self._map.get(sym_u)
        if cg_id:
            return cg_id
        if sym_u not in self._warned:
            self._warned.add(sym_u)
            log.warning(
                "no CoinGecko id mapped for %s — add to EXTRA_COINS in coingecko.py "
                "or run scripts/refresh_coin_map.py for a fresh top-N pull",
                symbol,
            )
        return None

    def historical_usd(self, cg_id: str, ts_ms: int) -> float | None:
        # No HTTP price lookup. Callers fall back to $0 cost basis.
        return None
