#!/usr/bin/env python3
"""One-shot helper that fetches the top-N coins by market cap from CoinGecko
and prints a `COIN_IDS` dict suitable for pasting into coingecko.py.

Run when you want to expand the hardcoded ticker → CoinGecko-ID map.
The runtime sync never calls CoinGecko itself; this is build-time only.

Usage:
    python3 scripts/refresh_coin_map.py [N]   # default N=100, max 250

Then copy the printed dict into the COIN_IDS literal in coingecko.py.
Keep any exchange-specific overrides (BGB, PROVE, etc.) that aren't in the top N.
"""

import json
import sys
import time
import urllib.error
import urllib.request

URL = "https://api.coingecko.com/api/v3/coins/markets"


def fetch(n: int) -> list[dict]:
    if n > 250:
        sys.exit("CoinGecko caps per_page at 250; use 250 or less")
    qs = (
        f"?vs_currency=usd&order=market_cap_desc&per_page={n}&page=1&sparkline=false"
    )
    for attempt in range(4):
        try:
            with urllib.request.urlopen(URL + qs, timeout=30) as r:
                return json.loads(r.read().decode())
        except urllib.error.HTTPError as e:
            if e.code == 429:
                wait = 60 * (attempt + 1)
                print(f"429 rate-limited; sleeping {wait}s...", file=sys.stderr)
                time.sleep(wait)
                continue
            raise
    sys.exit("gave up after 4 attempts")


def main() -> None:
    n = int(sys.argv[1]) if len(sys.argv) > 1 else 100
    coins = fetch(n)
    print(f"# Generated by scripts/refresh_coin_map.py — top {n} by market cap")
    print(f"# Fetched {time.strftime('%Y-%m-%d', time.gmtime())} UTC")
    print("COIN_IDS = {")
    for c in coins:
        sym = c["symbol"].upper()
        cg_id = c["id"]
        print(f'    "{sym}": "{cg_id}",')
    print("}")


if __name__ == "__main__":
    main()
